# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procurer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('numberOfDonors', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='createdAt')),
            ],
        ),
    ]
